In [63]:
import numpy as np
L = int(input("Length: "))
W = int(input("Width: "))
court = [list(map(int,input().split())) for i in range(L)]
one_fourtwo = np.full((4,2),1).tolist()
from copy import deepcopy
pointer_x = 0
pointer_y = 0
possible_lst = []
for i in range(len(court)):
    for j in range(len(court[0])):
        wait = []
        if len(court[i:i+4]) > 3:
            for row in court[i:i+4]:
                if len(row[j:j+2]) > 1:
                    #print(row[j:j+2])
                    wait.append(row[j:j+2])
            if not len(wait) == 0:
                u = deepcopy(court)
                if (one_fourtwo == wait) and (i != 0 and i+4 != len(u)-1 and j != 0 and j != len(u[0])-1):
                    #print('possible')
                    #print((i,i+4),(j,j+2))
                    for p in range(i,i+4):
                        for q in range(j,j+2):
                            u[p][q] = 'x'
                    possible_lst.append(u)
                #print()
print(f'{len(possible_lst)} possible court(s)')
for i in possible_lst:
    for p in range(len(i)):
        for q in range(len(i[p])):
            print(i[p][q],end=" ")
        print()
    print()

[[0 0 0 0]
 [0 1 0 1]
 [0 1 1 1]
 [1 1 1 1]
 [0 1 1 1]
 [0 1 1 1]
 [0 1 1 0]
 [0 0 0 0]]


2 possible court(s)
0 0 0 0 
0 1 0 1 
0 x x 1 
1 x x 1 
0 x x 1 
0 x x 1 
0 1 1 0 
0 0 0 0 

0 0 0 0 
0 1 0 1 
0 1 x x 
1 1 x x 
0 1 x x 
0 1 x x 
0 1 1 0 
0 0 0 0 



In [ ]:
import numpy as np
n = int(input('Input n: '))
m = int(input('Input m: '))
field = np.array([list(map(int,input().split())) for i in range(n)])
for i in list(range(np.min(field),np.max(field)+1)):
    finder = np.where(field == i)
    print(f"({finder[0][0]},{finder[1][0]})")

In [ ]:
def box_size(A,B,C):
    res = ""
    if B <= 10 and A <= 15 and C <= 8 :
        print("Box size 1 ")
        res = 1
    elif A <= 25 and B <= 15 and C <= 12 :
        print("Box size 2 ")
        res = 2
    elif B <= 40 and A <= 50 and C <= 20 :
        print("Box size 3 ")
        res = 3
    else:
        print("Oversize product")
        res = None
    return res
N = int(input("N: "))
total_box = {1 : 0 , 2 : 0 , 3 : 0}
for i in range(1,N+1):
    try:
        total_box[box_size(int(input(f"Order {i} A: ")),int(input(f"Order {i} B: ")),int(input(f"Order {i} C: ")))] += 1
    except KeyError:
        pass
for i in total_box:
    print(f"Use Box size {i}: {total_box[i]}")